import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { cborDecode } from '../src/cbor/decode';
import { asBytes, asText, mapGet } from '../src/cbor/model';
import { EvmDataType } from '../src/chains/evm';
import { SolSignType } from '../src/chains/solana';
import { bytesToHex } from '../src/core/bytes';
import { EraConnect } from '../src/index';
import { gunzipCapped } from '../src/tron-proto/gzip';

/**
 * Golden fixtures generated by the reference implementation's fixture
 * generator. For identical inputs this
 * SDK must produce BYTE-IDENTICAL request CBOR — that is the contract that
 * keeps it compatible with the device firmware. Deterministic synthetic
 * data; no real wallet material.
 */
const fixture = JSON.parse(
  readFileSync(join(__dirname, 'fixtures', 'golden-vectors.json'), 'utf8'),
) as {
  walletUr: string;
  requestIdHex: string;
  origin: string;
  wallet: Record<string, { accountPath: string; xfp: string } | string>;
  cases: {
    name: string;
    urType?: string;
    requestCborHex?: string;
    requestUr?: string;
    tronProtoHex?: string;
    tronOrigin?: string;
  }[];
};

const era = new EraConnect({ origin: fixture.origin });
const requestId = fixture.requestIdHex;
const caseByName = (name: string) => {
  const found = fixture.cases.find((c) => c.name === name);
  if (!found) throw new Error(`fixture case ${name} missing`);
  return found;
};

const signData = new Uint8Array(Array.from({ length: 40 }, (_, i) => i));
const bigSignData = new Uint8Array(Array.from({ length: 700 }, (_, i) => i % 251));
const address = new Uint8Array(20).fill(0xab);
const solPubkey = new Uint8Array(32).fill(0x07);
const psbt = new Uint8Array([
  0x70,
  0x73,
  0x62,
  0x74,
  0xff,
  ...Array.from({ length: 60 }, (_, i) => i),
]);
const tronRawData = new Uint8Array(Array.from({ length: 120 }, (_, i) => (i * 7) % 256));
const tronLatestBlock = {
  hash: '00000000045bcdc4c2ff1c56cf2b7ecdb60e0e26e3859ca9ff0a80b2f5502424',
  number: 73256388,
  timestamp: 1721908800000,
};

function expectGolden(
  name: string,
  ur: { type: string; cbor: Uint8Array; toWireString(): string },
) {
  const golden = caseByName(name);
  expect(ur.type).toBe(golden.urType);
  expect(bytesToHex(ur.cbor)).toBe(golden.requestCborHex);
  expect(ur.toWireString()).toBe(golden.requestUr);
}

describe('byte-exact golden requests vs the reference implementation', () => {
  it('links the reference wallet export', () => {
    const accounts = era.parseAccounts(fixture.walletUr);
    expect(accounts.masterFingerprint).toBe('deadbeef');
    expect(accounts.device.name).toBe('ERA Wallet');
    expect(accounts.device.id).toBe('TEST-DEVICE-ID');
    expect(accounts.device.firmwareVersion).toBe('9.9.9');
    expect(accounts.evm()?.xfp).toBe('11111111');
    expect(accounts.evm()?.accountPath).toBe("m/44'/60'/0'");
    expect(accounts.evm()?.pathFor(0)).toBe("m/44'/60'/0'/0/0");
    expect(accounts.btc()?.xfp).toBe('22222222');
    expect(accounts.tron()?.xfp).toBe('00abcdef');
    expect(accounts.solana()[0]?.xfp).toBe('33333333');
    expect(accounts.xfpFor("m/44'/195'/0'")).toBe('00abcdef');
  });

  it('evm_tx_bsc', () => {
    const req = era.evm.generateSignRequest({
      requestId,
      signData,
      dataType: EvmDataType.transaction,
      path: "m/44'/60'/0'/0/0",
      xfp: '11111111',
      chainId: 56,
      address,
    });
    expectGolden('evm_tx_bsc', req.ur);
  });

  it('evm_tx_aurora_large_chain_id', () => {
    const req = era.evm.generateSignRequest({
      requestId,
      signData: bigSignData,
      dataType: EvmDataType.typedTransaction,
      path: "m/44'/60'/0'/0/3",
      xfp: '11111111',
      chainId: 1313161554,
      address,
    });
    expectGolden('evm_tx_aurora_large_chain_id', req.ur);
  });

  it('evm_personal_message', () => {
    const req = era.evm.generateSignRequest({
      requestId,
      signData,
      dataType: EvmDataType.personalMessage,
      path: "m/44'/60'/0'/0/0",
      xfp: '11111111',
      chainId: 1,
      address,
    });
    expectGolden('evm_personal_message', req.ur);
  });

  it('evm_typed_data', () => {
    const req = era.evm.generateSignRequest({
      requestId,
      signData,
      dataType: EvmDataType.typedData,
      path: "m/44'/60'/0'/0/1",
      xfp: '11111111',
      chainId: 137,
      address,
    });
    expectGolden('evm_typed_data', req.ur);
  });

  it('btc_psbt', () => {
    const req = era.btc.generatePsbtSignRequest({ psbt });
    expectGolden('btc_psbt', req.ur);
    expect(req.requestId).toBeUndefined();
  });

  it('btc_message', () => {
    const req = era.btc.generateMessageSignRequest({
      requestId,
      message: signData,
      path: "m/84'/0'/0'/0/2",
      xfp: '22222222',
      address: '1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2',
    });
    expectGolden('btc_message', req.ur);
  });

  it('sol_tx and sol_message', () => {
    const tx = era.solana.generateSignRequest({
      requestId,
      signData,
      path: "m/44'/501'/0'",
      xfp: '33333333',
      publicKey: solPubkey,
    });
    expectGolden('sol_tx', tx.ur);

    const msg = era.solana.generateSignRequest({
      requestId,
      signData,
      signType: SolSignType.message,
      path: "m/44'/501'/0'",
      xfp: '33333333',
      publicKey: solPubkey,
    });
    expectGolden('sol_message', msg.ur);
  });

  function tronProtoOf(ur: { cbor: Uint8Array }): { protoHex: string; origin: string } {
    const map = cborDecode(ur.cbor);
    const compressed = asBytes(mapGet(map, 1));
    const origin = asText(mapGet(map, 2));
    if (!compressed || origin === undefined) throw new Error('bad tron request shape');
    // gzip BYTES are not comparable across implementations; the protobuf
    // underneath is the golden artifact.
    return { protoHex: bytesToHex(gunzipCapped(compressed, 64 * 1024)), origin };
  }

  it('tron_trc20', () => {
    const req = era.tron.generateSignRequest({
      requestId,
      rawData: tronRawData,
      path: "m/44'/195'/0'/0/5",
      xfp: '00abcdef',
      latestBlock: tronLatestBlock,
      display: {
        token: 'USDT',
        contractAddress: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
        from: 'TYPFhTLdUonqfhTJsuLdvBnWNiCdvvyyBt',
        to: 'TVjsyZ7fYF3qLF6BQgPmTEZy1xrNNyVAAA',
        value: '1000000',
        fee: 1000000,
      },
      timestamp: 0,
    });
    const golden = caseByName('tron_trc20');
    const { protoHex, origin } = tronProtoOf(req.ur);
    expect(req.ur.type).toBe('keystone-sign-request');
    expect(protoHex).toBe(golden.tronProtoHex);
    expect(origin).toBe(golden.tronOrigin);
  });

  it('tron_rawdata_only_display_empty', () => {
    const req = era.tron.generateSignRequest({
      requestId,
      rawData: tronRawData,
      path: "m/44'/195'/0'/0/0",
      xfp: '00abcdef',
      latestBlock: tronLatestBlock,
    });
    const golden = caseByName('tron_rawdata_only_display_empty');
    const { protoHex } = tronProtoOf(req.ur);
    expect(protoHex).toBe(golden.tronProtoHex);
  });
});
